sonar.projectKey=LazyCook
sonar.projectName=LazyCook
sonar.sourceEncoding=UTF-8

sonar.sources=project/backend,project/frontend
sonar.tests=project/backend/tests
sonar.test.inclusions=project/backend/tests/**/*.py
sonar.python.coverage.reportPaths=project/backend/coverage.xml
sonar.coverage.exclusions=project/frontend/**,project/backend/tests/**

sonar.exclusions=**/__pycache__/**,project/data/**,project/frontend/.next/**,project/frontend/node_modules/**,project/backend/coverage.xml
sonar.python.version=3.11
