services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "8000:8000"
    depends_on:
      - backend-dev

  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile-backend
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
      - GMAIL_USER=lazycook.noreply@gmail.com
      - GMAIL_PASSWORD= xavo fypu grhh sbur
    volumes:
      - ./data:/data
    ports:
      - "3000:3000"

# Persist data for containers
#volumes:
#  data:

#networks:
#  default:
#    driver: custom-driver