#FROM python:3.11.10-slim
#WORKDIR /app
#
#COPY backend/requirements.txt /app/requirements.txt
#RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt
#
#COPY /backend /app/
#
#CMD ["python", "main.py"]

#V2
FROM python:3.11.10-slim
WORKDIR /app

COPY Backend/requirements.txt /app/requirements.txt
RUN python -m pip install --upgrade pip
RUN python -m pip install --no-cache-dir -r /app/requirements.txt

COPY Backend/ /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

EXPOSE 8000

#CMD ["fastapi", "run", "main.py", "--port", "80"]
#CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000", "--workers", "4", "main:app"]
